apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-spanner
  name: hello-spanner
  namespace: hello
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-spanner
  sessionAffinity: None
  type: ClusterIP
